version: '2'

services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    user: root
    volumes:
      - /conf/elasticsearch/node2:/etc/elasticsearch/
    networks:
      elk_net:
        ipv4_address: 172.24.0.5

services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    user: root
    volumes:
      - /conf/elasticsearch/node1:/etc/elasticsearch/
    networks:
      elk_net:
        ipv4_address: 172.24.0.4




  logstash:
    image: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - /conf/logstash/config:/etc/logstash/conf.d:rw
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      - elasticsearch
    user: root
    networks:
      elk_net:
        ipv4_address: 172.24.0.3
#    extra_hosts:
#      - "elasticsearch:172.24.0.4"


  kibana:
    image: kibana
    volumes:
      - /conf/kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    user: root
    networks:
      elk_net:
        ipv4_address: 172.24.0.2
#    extra_hosts:
#      - "elasticsearch:172.24.0.4"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
        tag: "kibana"



networks:
  elk_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.24.0.0/24
        gateway: 172.24.0.1
