version: '2'

services:

  postgres-server:
    image: postgres:latest
    volumes:
      - /opt/CI/postgres:/var/lib/postgresql/data:rw
    env_file:
      - /opt/CI/ansible_containers/ansible/conf/.env_db_pgsql
    user: root
    networks:
      - zbx_net
    logging:
      driver: syslog
      options:
        tag: "postgre"


  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-3.2-latest
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/CI/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /opt/CI/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /opt/CI/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - /opt/CI/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - /opt/CI/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /opt/CI/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - /opt/CI/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
    env_file:
      - /opt/CI/ansible_containers/ansible/conf/.env_db_pgsql
      - /opt/CI/ansible_containers/ansible/conf/.env_srv
    user: root
    networks:
      - zbx_net
    logging:
      driver: syslog
      options:
        tag: "zabbix-server"

  apache:
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-latest
    ports:
      - "80:80"
    env_file:
      - /opt/CI/ansible_containers/ansible/conf/.env_db_pgsql
      - /opt/CI/ansible_containers/ansible/conf/.env_web
    user: root
    networks:
      - zbx_net
    logging:
      driver: syslog
      options:
        tag: "apache"



  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  logstash:
    image: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch



  kibana:
    image: kibana
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch


networks:
  zbx_net:
    driver: bridge
